### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by deki84** [deki84/capstone-project#12]
**Value Proposition**
As a user, you should be able to navigate through several pages, e.g. to see your crypto tracker and the news about it.

**Description**
<img width="375" alt="Capstone wireframe@2x" src="https://user-images.githubusercontent.com/35610295/193000423-0cc42e47-0cd8-4397-941e-24eecff47557.png">

- [ ] when clicking on Crypto you will get to a page where you can see the price chart and rank of the currency.
- [ ] when clicking on news you will get some news from the cryptos

**Tasks**
- [ ] create a navbar in the header
- [ ] create a footer 
- [ ] create router to navigate multiple pages
