### ISSUE TITLE
Create a crypto ranking 

### ISSUE THREAD

**Issue by deki84** [deki84/capstone-project#14]
**Value Proposition**
As a user, I would like to know the value of my cryptocurrencies.

**Description**
<img width="375" alt="Capstone wireframe@2x" src="https://user-images.githubusercontent.com/35610295/193773726-c7934eec-f20e-4b84-8d74-a4255baa819c.png">

**Acceptance Criteria**
- [ ] The user sees the top 100 currencies by Price, Volume , Change(24), Market Cap
- [ ] The user can search for a coin in the search function
 
**Tasks**
- [ ] Use a UseEffect du fetching the data you needed (Price,Volume,Change(24h), Market Cap
- [ ] create a form for the searching input
- [ ] Create a Coin component in which you make a map to see all the data and images on the page.

**Comment by StefanieLoeser** [comment]
Hey Deki, looks pretty good already :)
The selection of a coin is probably planned for another user-story, right?

**Comment by deki84** [comment]
No, this is only for this user story.
