### ISSUE TITLE
create news page

### ISSUE THREAD

**Issue by deki84** [deki84/capstone-project#16]
**Value Proposition**
As a user I would like to have the latest information about crypto.

**Description** 
<img width="375" alt="Capstone wireframe@2x" src="https://user-images.githubusercontent.com/35610295/194321589-56668d56-84b2-4368-8f8d-1bc3a945bf0f.png">

**Acceptance Criteria**
- [ ]  user can scroll down and choose the news he is interested in
- [ ]  user can click on a link and will be redirected to the news page.

**Tasks** 
- [ ] use a useEffect and fetch api for the news
- [ ] create a NewsList Component
- [ ] map the api for the data 
- [ ] style the page

**Comment by mbosselmann** [comment]
Hi Dejan,
I think your user story is good. I just wonder if I understand it correctly that when you click on an article you are redirected to a detail page to read that article? To describe this in more detail and also to show it as a wireframe would be missing for me to understand your user story well. :)

**Comment by deki84** [comment]
Yes, you have understood correctly. I will rewrite this for your understanding.
