### ISSUE TITLE
select Coin

### ISSUE THREAD

**Issue by deki84** [deki84/capstone-project#18]
**Value Proposition**
As a user, you would also like to be able to choose another coin.

**Description**
<img width="412" alt="Screenshot 2022-10-09 at 21 09 43" src="https://user-images.githubusercontent.com/35610295/194776735-e996d31e-8f42-4571-9f31-d0fcd096e84d.png">

Acceptance Criteria
- [ ] If the user clicks on select coin he can choose a coin.
- [ ] The programme calculates the selected coin

**Tasks**
- [ ]  create a drop menu
- [ ] create a function calculation for the calculation 
- [ ] map coins for value
- [ ] style drop menu
