### ISSUE TITLE
input fields and heading

### ISSUE THREAD

**Issue by deki84** [deki84/capstone-project#2]
**Value Proposition**

As a crypto enthusiast, I need to know how many months I can live on my crypto assets. 
crypto assets so that I can get an overview of my financial situation in the cryptocurrency sector.

**Description**

![Capstone wireframe Task 1](https://user-images.githubusercontent.com/35610295/190625928-3f37e909-1f27-4ca7-8feb-d1bb171df540.png)

**Acceptance Criteria**
- [ ] when clicking on the first input field any text can be written
- [ ] When clicking on the second input field, the cryptocurrency can be selected
- [ ] when clicking on the (click me) button the program calculates the assets
- [ ] when clicking the (click me) button without inputs, an alert will pop up with an error message
- [ ] the input has a max length of 240 characters

**Tasks**
- [ ] create a branch
- [ ] create h1 for CryptoCalc
- [ ] create input fields and a button 
- [ ] create a program how calculate the assets

**Comment by macfrei** [comment]
Looks great! 👍
