### ISSUE TITLE
answer text and refresh button 

### ISSUE THREAD

**Issue by deki84** [deki84/capstone-project#5]
**Value Proposition**
As a user u need to get an answer question about your money you have .
The Refresh button is used to determine your current crypto price.

**Description**
![Capstone wireframe step 2](https://user-images.githubusercontent.com/35610295/190383743-60fac7d7-4720-400a-b747-cce34442e6d7.png)

**Acceptance Criteria**

- [ ] after click a (click me) button you get a value by this time 
- [ ] As the prices change every second, you must press the refresh button so that the program knows what it is currently calculating.

**Tasks**

- [ ] create a form as a answer text 
- [ ] create refresh button for current price
